[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "neuronol"
version = "0.0.5a"
# dynamic = ["version"]
dependencies = [
  "mne",
  "numpy",
  "scipy",
  "pandas",
]
requires-python = ">=3.14"
authors = [
  { name="Parth Chholak", email="parthchholak@gmail.com" },
]
description = "Package for working with EEG and MR biomarkers of AUD."
readme = "README.md"
license = "LicenseRef-Adapted-CC0"
license-files = ["LICENSE.md"]
keywords = ["eeg", "meg", "m/eeg", "mri", "fmri", "neuroimaging", "ai", "ml", "addiction", "aud"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]

[project.optional-dependencies]
dev = ["pytest", "dotenv"]

[project.urls]
Repository = "https://github.com/chholakp2NIH/neuronol"
Issues = "https://github.com/chholakp2NIH/neuronol/issues"
