services:
  auto-data-importer:
    container_name: "neuronol-auto-data-importer"
    build:
      context: ../../..
      dockerfile: examples/data_import/watcher+db/Dockerfile
    restart: unless-stopped
    environment:
      EXAMPLE_DATA_DIR: /data # sets env var inside the container
      TZ: America/New_York
    volumes:
      # - ${HOME}/data/bids/imotions-sample:/data
      - ${HOME}/data/bids/eegacamp-test:/data
